name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Dummy envs so Next.js build and Clerk provider mount cleanly
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_Y2ktZHVtbXktZm9yLWJ1aWxkLXRlc3QtcHVycG9zZXMtb25seQ
      CLERK_SECRET_KEY: sk_test_Y2ktZHVtbXktZm9yLWJ1aWxkLXRlc3QtcHVycG9zZXMtb25seQ
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run fmt:check

      - name: Typecheck
        run: npm run typecheck

      - name: Tests
        run: npm test

      - name: Build
        run: npm run build
