name: Cleanup Test Accounts

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual trigger
    inputs:
      dry_run:
        description: 'Perform a dry run (no actual deletions)'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd scripts && npm install tsx

      - name: Run cleanup script
        run: |
          if [ "${{ github.event.inputs.dry_run }}" = "false" ]; then
            cd scripts && npx tsx cleanup-test-accounts.ts
          else
            cd scripts && npx tsx cleanup-test-accounts.ts --dry-run
          fi
        env:
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}

      - name: Notify completion
        run: echo "✅ Test account cleanup completed!"
